language: python
cache: pip
os:
  - linux
python:
  - 3.6
  - 3.7
  - 3.8
sudo: false
env:
  - TOXENV="py${PYTHON_VERSION//./}"
install:
  - pip install tox
script: tox
after_success:
    - pip install codecov
    - codecov -e TOXENV
