# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-04-12 17:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websubsub', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscribe_status',
            field=models.CharField(choices=[('requesting', 'scheduled to be requested asap'), ('connerror', 'connection error'), ('huberror', 'hub returned error'), ('verifying', 'waiting for hub verification request'), ('verifyerror', 'hub sent malformed verification request'), ('verified', 'verified'), ('denied', 'hub denied subscription')], default='requesting', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='unsubscribe_status',
            field=models.CharField(blank=True, choices=[('requesting', 'scheduled to be requested asap'), ('connerror', 'connection error'), ('huberror', 'hub returned error'), ('verifying', 'waiting for hub verification request'), ('verifyerror', 'hub sent malformed verification request'), ('verified', 'verified')], max_length=20, null=True),
        ),
    ]
