# Generated by Django 2.0.13 on 2020-02-14 22:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('websubsub', '0002_auto_20180412_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, null=True),
        ),
    ]
