# Generated by Django 2.0.13 on 2020-02-14 22:04

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Subscription = apps.get_model('websubsub', 'Subscription')
    for row in Subscription.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=['uuid'])

class Migration(migrations.Migration):

    dependencies = [
        ('websubsub', '0003_subscription_uuid'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop)
    ]
