# Generated by Django 2.0.13 on 2020-02-14 22:04
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websubsub', '0004_populate_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
