# Generated by Django 2.0.13 on 2020-02-14 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websubsub', '0006_auto_20200215_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='uuid',
            new_name='id',
        ),
    ]
