# Generated by Django 2.0.13 on 2020-02-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websubsub', '0009_auto_20200215_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='time_last_event_received',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
