# Generated by Django 2.0.13 on 2020-02-21 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websubsub', '0011_subscription_static'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscribe_status',
            field=models.CharField(choices=[('requesting', 'scheduled to be requested asap'), ('connerror', 'connection error'), ('huberror', 'hub returned error'), ('verifying', 'waiting for hub to send us subscription confirmation request'), ('verifyerror', 'hub sent us malformed subscription confirmation request'), ('verified', 'verified'), ('denied', 'hub denied subscription')], default='requesting', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='unsubscribe_status',
            field=models.CharField(blank=True, choices=[('requesting', 'scheduled to be requested asap'), ('connerror', 'connection error'), ('huberror', 'hub returned error'), ('verifying', 'waiting for hub to send us subscription confirmation request'), ('verifyerror', 'hub sent us malformed subscription confirmation request'), ('verified', 'verified')], max_length=20, null=True),
        ),
    ]
